// <auto-generated />
namespace EFTransaction.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddProducts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddProducts));
        
        string IMigrationMetadata.Id
        {
            get { return "201212060425411_AddProducts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
